//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SzlqTech.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SzlqTech.Localization.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序集 的本地化字符串。
        /// </summary>
        public static string Assembly {
            get {
                return ResourceManager.GetString("Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图表展示 的本地化字符串。
        /// </summary>
        public static string ChartView {
            get {
                return ResourceManager.GetString("ChartView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代码 的本地化字符串。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置管理 的本地化字符串。
        /// </summary>
        public static string ConfingManagment {
            get {
                return ResourceManager.GetString("ConfingManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据采集 的本地化字符串。
        /// </summary>
        public static string DataCollection {
            get {
                return ResourceManager.GetString("DataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据查询 的本地化字符串。
        /// </summary>
        public static string DataQuery {
            get {
                return ResourceManager.GetString("DataQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入产品二维码 的本地化字符串。
        /// </summary>
        public static string DataQueryHintText {
            get {
                return ResourceManager.GetString("DataQueryHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据类型 的本地化字符串。
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认导航页面 的本地化字符串。
        /// </summary>
        public static string DefaultNavigateView {
            get {
                return ResourceManager.GetString("DefaultNavigateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        public static string DeleteErrorMsg {
            get {
                return ResourceManager.GetString("DeleteErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string DeleteSuccessMsg {
            get {
                return ResourceManager.GetString("DeleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用心跳键 的本地化字符串。
        /// </summary>
        public static string EnableHeartbeatKey {
            get {
                return ResourceManager.GetString("EnableHeartbeatKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用扫描 的本地化字符串。
        /// </summary>
        public static string EnableScan {
            get {
                return ResourceManager.GetString("EnableScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入站时间 的本地化字符串。
        /// </summary>
        public static string EnterDate {
            get {
                return ResourceManager.GetString("EnterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败 的本地化字符串。
        /// </summary>
        public static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忘记密码 的本地化字符串。
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入菜单 的本地化字符串。
        /// </summary>
        public static string ImportMenu {
            get {
                return ResourceManager.GetString("ImportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 苏州旭创 的本地化字符串。
        /// </summary>
        public static string InnoLight {
            get {
                return ResourceManager.GetString("InnoLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择语言 的本地化字符串。
        /// </summary>
        public static string LangSelected {
            get {
                return ResourceManager.GetString("LangSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出站时间 的本地化字符串。
        /// </summary>
        public static string LeaveDate {
            get {
                return ResourceManager.GetString("LeaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录错误，请重新输入用户名或密码 的本地化字符串。
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string LoginIn {
            get {
                return ResourceManager.GetString("LoginIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出登录 的本地化字符串。
        /// </summary>
        public static string LoginOut {
            get {
                return ResourceManager.GetString("LoginOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器列表详情 的本地化字符串。
        /// </summary>
        public static string MachineDetail {
            get {
                return ResourceManager.GetString("MachineDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器配置 的本地化字符串。
        /// </summary>
        public static string MachineManagement {
            get {
                return ResourceManager.GetString("MachineManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单分配 的本地化字符串。
        /// </summary>
        public static string MenuAssign {
            get {
                return ResourceManager.GetString("MenuAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单导入 的本地化字符串。
        /// </summary>
        public static string MenuImport {
            get {
                return ResourceManager.GetString("MenuImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化 的本地化字符串。
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面名称 的本地化字符串。
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请重新启动软件 的本地化字符串。
        /// </summary>
        public static string PleaseRestorSystem {
            get {
                return ResourceManager.GetString("PleaseRestorSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口键 的本地化字符串。
        /// </summary>
        public static string PortKey {
            get {
                return ResourceManager.GetString("PortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品 的本地化字符串。
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品代码 的本地化字符串。
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品管理 的本地化字符串。
        /// </summary>
        public static string ProductManagement {
            get {
                return ResourceManager.GetString("ProductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称 的本地化字符串。
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品二维码 的本地化字符串。
        /// </summary>
        public static string ProductQrCode {
            get {
                return ResourceManager.GetString("ProductQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品为空，请选择产品 的本地化字符串。
        /// </summary>
        public static string ProudctSelectedNull {
            get {
                return ResourceManager.GetString("ProudctSelectedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住密码 的本地化字符串。
        /// </summary>
        public static string RememberPassword {
            get {
                return ResourceManager.GetString("RememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        public static string RoleManager {
            get {
                return ResourceManager.GetString("RoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色选择 的本地化字符串。
        /// </summary>
        public static string RoleSelection {
            get {
                return ResourceManager.GetString("RoleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描设备 的本地化字符串。
        /// </summary>
        public static string ScanEquipment {
            get {
                return ResourceManager.GetString("ScanEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描配置 的本地化字符串。
        /// </summary>
        public static string ScanManagement {
            get {
                return ResourceManager.GetString("ScanManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描周期(ms) 的本地化字符串。
        /// </summary>
        public static string ScannCycle {
            get {
                return ResourceManager.GetString("ScannCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动失败 的本地化字符串。
        /// </summary>
        public static string StartError {
            get {
                return ResourceManager.GetString("StartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动成功 的本地化字符串。
        /// </summary>
        public static string StartSuccess {
            get {
                return ResourceManager.GetString("StartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工站 的本地化字符串。
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工站名称 的本地化字符串。
        /// </summary>
        public static string StationName {
            get {
                return ResourceManager.GetString("StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止失败 的本地化字符串。
        /// </summary>
        public static string StopError {
            get {
                return ResourceManager.GetString("StopError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止成功 的本地化字符串。
        /// </summary>
        public static string StopSuccess {
            get {
                return ResourceManager.GetString("StopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string SuccessMsg {
            get {
                return ResourceManager.GetString("SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        public static string SysConfig {
            get {
                return ResourceManager.GetString("SysConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string UserManager {
            get {
                return ResourceManager.GetString("UserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作流程 的本地化字符串。
        /// </summary>
        public static string WorkFlow {
            get {
                return ResourceManager.GetString("WorkFlow", resourceCulture);
            }
        }
    }
}
